### ISSUE TITLE
'export' command is valid only for unix shells. In Windows - use 'set' instead of 'export'

### ISSUE THREAD

**Issue by miesterium** [atulmy/crate#1]
Hi Atul , 
please use 'set' instead of 'export' . im getting error on section : npm start

$ npm start

> web@1.0.0 start C:\Users\Administrator\Desktop\crate-master\code\web
> export NODE_ENV=development && npm run build && nodemon --exec babel-node -- src/setup/server/index.js

'export' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web@1.0.0 start: `export NODE_ENV=development && npm run build && nodemon --exec babel-node -- src/setup/server/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the web@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-04-18T07_37_12_626Z-debug.log

**Comment by atulmy** [comment]
Hi @miesterium, I recommend you to use any of following:

- Bash on Windows (comes along with when you install Git)
- Containerization using Docker
- `cross-env` https://github.com/kentcdodds/cross-env

I've not added `cross-env` package in order to keep the number of dependencies less and also 'configuration' part as minimal as possible.
