### ISSUE TITLE
not able to register a user

### ISSUE THREAD

**Issue by cavapoo2** [atulmy/crate#7]
Seem like when i choose 'Create and account', when i try to enter a name or email or password, the cursor does not advance forward. Seems like its being reset to the start each time or overwritten with empty space.

**Comment by atulmy** [comment]
@cavapoo2 is this in case of `mobile` or `web`?

**Comment by cavapoo2** [comment]
hi, im using the web example.

**Comment by cavapoo2** [comment]
im sure there's better way but this seem to fix it 
```

		if (event.target.name === 'name')
		{
			this.setState({
				user:{name:event.target.value}
			})

		}
		else if(event.target.name === 'email')
		{
			this.setState({
				user:{email:event.target.value}
			})

		}
		else
		{
			this.setState({
				user:{password:event.target.value}
			})

		}

```

**Comment by cavapoo2** [comment]
at least i can type something and it seems to register ok. now get same issue with login, so maybe simialr issue

**Comment by atulmy** [comment]
Hey @cavapoo2, the issue arose because of changing React components from `Component` to `PureComponent` as `PureComponent`'s `shouldComponentUpdate` will not consider deeper object and block re-render for eg:

Wont work in case of `PureComponent`:
```
this.state = {
  user: {
    email: '',
    password: '',
  }
} 
```
Works in case of `PureComponent`:
```
this.state = {
  email: '',
  password: '',
} 
```

I've resolved this issue. Thank you for reporting the bug.
